import type { INodePropertyOptions } from 'n8n-workflow';

/**
 * Events an outgoing webhook can deliver, from the Bitrix24 REST documentation
 * (2026-09-14). Generated — the event list method itself refuses
 * inbound webhooks, so the portal cannot be asked. Anything missing can be typed
 * into Other Event Codes.
 */
export const EVENT_OPTIONS: INodePropertyOptions[] = [
	{ name: 'Booking Added', value: 'ONBOOKINGADD' },
	{ name: 'Booking Deleted', value: 'ONBOOKINGDELETE' },
	{ name: 'Booking Resource Added', value: 'ONBOOKINGRESOURCEADD' },
	{ name: 'Booking Resource Deleted (ONBOOKINGRESOURCEDELETE)', value: 'ONBOOKINGRESOURCEDELETE' },
	{ name: 'Booking Resource Deleted (ONRESOURCEDELETE)', value: 'ONRESOURCEDELETE' },
	{ name: 'Booking Resource Type Added', value: 'ONBOOKINGRESOURCETYPEADD' },
	{ name: 'Booking Resource Type Deleted', value: 'ONBOOKINGRESOURCETYPEDELETE' },
	{ name: 'Booking Resource Type Updated', value: 'ONBOOKINGRESOURCETYPEUPDATE' },
	{ name: 'Booking Resource Updated', value: 'ONBOOKINGRESOURCEUPDATE' },
	{ name: 'Booking Updated', value: 'ONBOOKINGUPDATE' },
	{ name: 'Booking Waitlist Item Added', value: 'ONBOOKINGWAITLISTITEMADD' },
	{ name: 'Booking Waitlist Item Deleted', value: 'ONBOOKINGWAITLISTITEMDELETE' },
	{ name: 'Booking Waitlist Item Updated', value: 'ONBOOKINGWAITLISTITEMUPDATE' },
	{ name: 'Booking Waitlist Record Being Deleted', value: 'ONDELETINGRECORDFROMWAITLIST' },
	{ name: 'Calendar Added', value: 'ONCALENDARSECTIONADD' },
	{ name: 'Calendar Deleted', value: 'ONCALENDARSECTIONDELETE' },
	{ name: 'Calendar Event Added', value: 'ONCALENDARENTRYADD' },
	{ name: 'Calendar Event Deleted', value: 'ONCALENDARENTRYDELETE' },
	{ name: 'Calendar Event Updated', value: 'ONCALENDARENTRYUPDATE' },
	{ name: 'Calendar Updated', value: 'ONCALENDARSECTIONUPDATE' },
	{ name: 'Chat Bot (Old) Deleted', value: 'ONIMBOTDELETE' },
	{ name: 'Chat Bot (Old) Joined a Chat', value: 'ONIMBOTJOINCHAT' },
	{ name: 'Chat Bot (Old) Message Added', value: 'ONIMBOTMESSAGEADD' },
	{ name: 'Chat Bot (Old) Message Deleted', value: 'ONIMBOTMESSAGEDELETE' },
	{ name: 'Chat Bot (Old) Message Updated', value: 'ONIMBOTMESSAGEUPDATE' },
	{ name: 'Chat Bot Command Used', value: 'ONIMBOTV2COMMANDADD' },
	{ name: 'Chat Bot Context Requested', value: 'ONIMBOTV2CONTEXTGET' },
	{ name: 'Chat Bot Deleted', value: 'ONIMBOTV2DELETE' },
	{ name: 'Chat Bot Joined a Chat', value: 'ONIMBOTV2JOINCHAT' },
	{ name: 'Chat Bot Message Added', value: 'ONIMBOTV2MESSAGEADD' },
	{ name: 'Chat Bot Message Deleted', value: 'ONIMBOTV2MESSAGEDELETE' },
	{ name: 'Chat Bot Message Updated', value: 'ONIMBOTV2MESSAGEUPDATE' },
	{ name: 'Chat Bot Reaction Changed', value: 'ONIMBOTV2REACTIONCHANGE' },
	{ name: 'Chat Command Added', value: 'ONIMCOMMANDADD' },
	{ name: 'Chat Joined a Chat', value: 'ONIMV2JOINCHAT' },
	{ name: 'Chat Message Added', value: 'ONIMV2MESSAGEADD' },
	{ name: 'Chat Message Deleted', value: 'ONIMV2MESSAGEDELETE' },
	{ name: 'Chat Message Updated', value: 'ONIMV2MESSAGEUPDATE' },
	{ name: 'Chat Reaction Changed', value: 'ONIMV2REACTIONCHANGE' },
	{ name: 'CRM Activity Added', value: 'ONCRMACTIVITYADD' },
	{ name: 'CRM Activity Deleted', value: 'ONCRMACTIVITYDELETE' },
	{ name: 'CRM Activity Updated', value: 'ONCRMACTIVITYUPDATE' },
	{ name: 'CRM Address Added', value: 'ONCRMADDRESSREGISTER' },
	{ name: 'CRM Address Removed', value: 'ONCRMADDRESSUNREGISTER' },
	{ name: 'CRM Bank Detail Added', value: 'ONCRMBANKDETAILADD' },
	{ name: 'CRM Bank Detail Deleted', value: 'ONCRMBANKDETAILDELETE' },
	{ name: 'CRM Bank Detail Updated', value: 'ONCRMBANKDETAILUPDATE' },
	{ name: 'CRM Company Added', value: 'ONCRMCOMPANYADD' },
	{ name: 'CRM Company Custom Field Added', value: 'ONCRMCOMPANYUSERFIELDADD' },
	{ name: 'CRM Company Custom Field Deleted', value: 'ONCRMCOMPANYUSERFIELDDELETE' },
	{ name: 'CRM Company Custom Field List Values Set', value: 'ONCRMCOMPANYUSERFIELDSETENUMVALUES' },
	{ name: 'CRM Company Custom Field Updated', value: 'ONCRMCOMPANYUSERFIELDUPDATE' },
	{ name: 'CRM Company Deleted', value: 'ONCRMCOMPANYDELETE' },
	{ name: 'CRM Company Updated', value: 'ONCRMCOMPANYUPDATE' },
	{ name: 'CRM Contact Added', value: 'ONCRMCONTACTADD' },
	{ name: 'CRM Contact Custom Field Added', value: 'ONCRMCONTACTUSERFIELDADD' },
	{ name: 'CRM Contact Custom Field Deleted', value: 'ONCRMCONTACTUSERFIELDDELETE' },
	{ name: 'CRM Contact Custom Field List Values Set', value: 'ONCRMCONTACTUSERFIELDSETENUMVALUES' },
	{ name: 'CRM Contact Custom Field Updated', value: 'ONCRMCONTACTUSERFIELDUPDATE' },
	{ name: 'CRM Contact Deleted', value: 'ONCRMCONTACTDELETE' },
	{ name: 'CRM Contact Updated', value: 'ONCRMCONTACTUPDATE' },
	{ name: 'CRM Currency Added', value: 'ONCRMCURRENCYADD' },
	{ name: 'CRM Currency Deleted', value: 'ONCRMCURRENCYDELETE' },
	{ name: 'CRM Currency Updated', value: 'ONCRMCURRENCYUPDATE' },
	{ name: 'CRM Deal Added', value: 'ONCRMDEALADD' },
	{ name: 'CRM Deal Created From Recurring Template', value: 'ONCRMDEALRECURRINGEXPOSE' },
	{ name: 'CRM Deal Custom Field Added', value: 'ONCRMDEALUSERFIELDADD' },
	{ name: 'CRM Deal Custom Field Deleted', value: 'ONCRMDEALUSERFIELDDELETE' },
	{ name: 'CRM Deal Custom Field List Values Set', value: 'ONCRMDEALUSERFIELDSETENUMVALUES' },
	{ name: 'CRM Deal Custom Field Updated', value: 'ONCRMDEALUSERFIELDUPDATE' },
	{ name: 'CRM Deal Deleted', value: 'ONCRMDEALDELETE' },
	{ name: 'CRM Deal Moved to Another Pipeline', value: 'ONCRMDEALMOVETOCATEGORY' },
	{ name: 'CRM Deal Recurring Template Added', value: 'ONCRMDEALRECURRINGADD' },
	{ name: 'CRM Deal Recurring Template Deleted', value: 'ONCRMDEALRECURRINGDELETE' },
	{ name: 'CRM Deal Recurring Template Updated', value: 'ONCRMDEALRECURRINGUPDATE' },
	{ name: 'CRM Deal Updated', value: 'ONCRMDEALUPDATE' },
	{ name: 'CRM Document Added', value: 'ONCRMDOCUMENTGENERATORDOCUMENTADD' },
	{ name: 'CRM Document Deleted', value: 'ONCRMDOCUMENTGENERATORDOCUMENTDELETE' },
	{ name: 'CRM Document Updated', value: 'ONCRMDOCUMENTGENERATORDOCUMENTUPDATE' },
	{ name: 'CRM Invoice (Old) Added', value: 'ONCRMINVOICEADD' },
	{ name: 'CRM Invoice (Old) Created From Recurring Template', value: 'ONCRMINVOICERECURRINGEXPOSE' },
	{ name: 'CRM Invoice (Old) Custom Field Added', value: 'ONCRMINVOICEUSERFIELDADD' },
	{ name: 'CRM Invoice (Old) Custom Field Deleted', value: 'ONCRMINVOICEUSERFIELDDELETE' },
	{ name: 'CRM Invoice (Old) Custom Field List Values Set', value: 'ONCRMINVOICEUSERFIELDSETENUMVALUES' },
	{ name: 'CRM Invoice (Old) Custom Field Updated', value: 'ONCRMINVOICEUSERFIELDUPDATE' },
	{ name: 'CRM Invoice (Old) Deleted', value: 'ONCRMINVOICEDELETE' },
	{ name: 'CRM Invoice (Old) Recurring Template Added', value: 'ONCRMINVOICERECURRINGADD' },
	{ name: 'CRM Invoice (Old) Recurring Template Deleted', value: 'ONCRMINVOICERECURRINGDELETE' },
	{ name: 'CRM Invoice (Old) Recurring Template Updated', value: 'ONCRMINVOICERECURRINGUPDATE' },
	{ name: 'CRM Invoice (Old) Status Changed', value: 'ONCRMINVOICESETSTATUS' },
	{ name: 'CRM Invoice (Old) Updated', value: 'ONCRMINVOICEUPDATE' },
	{ name: 'CRM Lead Added', value: 'ONCRMLEADADD' },
	{ name: 'CRM Lead Custom Field Added', value: 'ONCRMLEADUSERFIELDADD' },
	{ name: 'CRM Lead Custom Field Deleted', value: 'ONCRMLEADUSERFIELDDELETE' },
	{ name: 'CRM Lead Custom Field List Values Set', value: 'ONCRMLEADUSERFIELDSETENUMVALUES' },
	{ name: 'CRM Lead Custom Field Updated', value: 'ONCRMLEADUSERFIELDUPDATE' },
	{ name: 'CRM Lead Deleted (ONCRMLEADDELETE)', value: 'ONCRMLEADDELETE' },
	{ name: 'CRM Lead Deleted (ONLEADDELETE)', value: 'ONLEADDELETE' },
	{ name: 'CRM Lead Updated', value: 'ONCRMLEADUPDATE' },
	{ name: 'CRM Measure Added', value: 'ONCRMMEASUREADD' },
	{ name: 'CRM Measure Deleted', value: 'ONCRMMEASUREDELETE' },
	{ name: 'CRM Measure Updated', value: 'ONCRMMEASUREUPDATE' },
	{ name: 'CRM Product Added', value: 'ONCRMPRODUCTADD' },
	{ name: 'CRM Product Deleted', value: 'ONCRMPRODUCTDELETE' },
	{ name: 'CRM Product Property Added', value: 'ONCRMPRODUCTPROPERTYADD' },
	{ name: 'CRM Product Property Deleted', value: 'ONCRMPRODUCTPROPERTYDELETE' },
	{ name: 'CRM Product Property Updated', value: 'ONCRMPRODUCTPROPERTYUPDATE' },
	{ name: 'CRM Product Section Added', value: 'ONCRMPRODUCTSECTIONADD' },
	{ name: 'CRM Product Section Deleted', value: 'ONCRMPRODUCTSECTIONDELETE' },
	{ name: 'CRM Product Section Updated', value: 'ONCRMPRODUCTSECTIONUPDATE' },
	{ name: 'CRM Product Updated', value: 'ONCRMPRODUCTUPDATE' },
	{ name: 'CRM Quote Added', value: 'ONCRMQUOTEADD' },
	{ name: 'CRM Quote Custom Field Added', value: 'ONCRMQUOTEUSERFIELDADD' },
	{ name: 'CRM Quote Custom Field Deleted', value: 'ONCRMQUOTEUSERFIELDDELETE' },
	{ name: 'CRM Quote Custom Field List Values Set', value: 'ONCRMQUOTEUSERFIELDSETENUMVALUES' },
	{ name: 'CRM Quote Custom Field Updated', value: 'ONCRMQUOTEUSERFIELDUPDATE' },
	{ name: 'CRM Quote Deleted', value: 'ONCRMQUOTEDELETE' },
	{ name: 'CRM Quote Updated', value: 'ONCRMQUOTEUPDATE' },
	{ name: 'CRM Requisite Added', value: 'ONCRMREQUISITEADD' },
	{ name: 'CRM Requisite Custom Field Added', value: 'ONCRMREQUISITEUSERFIELDADD' },
	{ name: 'CRM Requisite Custom Field Deleted', value: 'ONCRMREQUISITEUSERFIELDDELETE' },
	{ name: 'CRM Requisite Custom Field List Values Set', value: 'ONCRMREQUISITEUSERFIELDSETENUMVALUES' },
	{ name: 'CRM Requisite Custom Field Updated', value: 'ONCRMREQUISITEUSERFIELDUPDATE' },
	{ name: 'CRM Requisite Deleted', value: 'ONCRMREQUISITEDELETE' },
	{ name: 'CRM Requisite Updated', value: 'ONCRMREQUISITEUPDATE' },
	{ name: 'CRM Smart Process Item Added', value: 'ONCRMDYNAMICITEMADD' },
	{ name: 'CRM Smart Process Item Deleted', value: 'ONCRMDYNAMICITEMDELETE' },
	{ name: 'CRM Smart Process Item Updated', value: 'ONCRMDYNAMICITEMUPDATE' },
	{ name: 'CRM Smart Process Type Added', value: 'ONCRMTYPEADD' },
	{ name: 'CRM Smart Process Type Custom Field Added', value: 'ONCRMTYPEUSERFIELDADD' },
	{ name: 'CRM Smart Process Type Custom Field Deleted', value: 'ONCRMTYPEUSERFIELDDELETE' },
	{ name: 'CRM Smart Process Type Custom Field List Values Set', value: 'ONCRMTYPEUSERFIELDSETENUMVALUES' },
	{ name: 'CRM Smart Process Type Custom Field Updated', value: 'ONCRMTYPEUSERFIELDUPDATE' },
	{ name: 'CRM Smart Process Type Deleted', value: 'ONCRMTYPEDELETE' },
	{ name: 'CRM Smart Process Type Updated', value: 'ONCRMTYPEUPDATE' },
	{ name: 'CRM Timeline Comment Added', value: 'ONCRMTIMELINECOMMENTADD' },
	{ name: 'CRM Timeline Comment Deleted', value: 'ONCRMTIMELINECOMMENTDELETE' },
	{ name: 'CRM Timeline Comment Updated', value: 'ONCRMTIMELINECOMMENTUPDATE' },
	{ name: 'E-Signature Document Status Changed', value: 'ONSIGNB2EDOCUMENTSTATUSCHANGED' },
	{ name: 'E-Signature Signer Status Changed', value: 'ONSIGNB2EMEMBERSTATUSCHANGED' },
	{ name: 'External Call Started', value: 'ONEXTERNALCALLSTART' },
	{ name: 'External Callback Started', value: 'ONEXTERNALCALLBACKSTART' },
	{ name: 'Feed Post Added', value: 'ONLIVEFEEDPOSTADD' },
	{ name: 'Feed Post Deleted', value: 'ONLIVEFEEDPOSTDELETE' },
	{ name: 'Feed Post Updated', value: 'ONLIVEFEEDPOSTUPDATE' },
	{ name: 'HR E-Signature Document Signed', value: 'ONSIGNHCMLINKB2EDOCUMENTSIGNED' },
	{ name: 'Open Channel Connector Dialog Finished', value: 'ONIMCONNECTORDIALOGFINISH' },
	{ name: 'Open Channel Connector Dialog Started', value: 'ONIMCONNECTORDIALOGSTART' },
	{ name: 'Open Channel Connector Line Deleted', value: 'ONIMCONNECTORLINEDELETE' },
	{ name: 'Open Channel Connector Message Added', value: 'ONIMCONNECTORMESSAGEADD' },
	{ name: 'Open Channel Connector Message Deleted', value: 'ONIMCONNECTORMESSAGEDELETE' },
	{ name: 'Open Channel Connector Message Updated', value: 'ONIMCONNECTORMESSAGEUPDATE' },
	{ name: 'Open Channel Connector Status Deleted', value: 'ONIMCONNECTORSTATUSDELETE' },
	{ name: 'Open Channel Message Added', value: 'ONOPENLINEMESSAGEADD' },
	{ name: 'Open Channel Message Deleted', value: 'ONOPENLINEMESSAGEDELETE' },
	{ name: 'Open Channel Message Updated', value: 'ONOPENLINEMESSAGEUPDATE' },
	{ name: 'Open Channel Session Finished', value: 'ONSESSIONFINISH' },
	{ name: 'Open Channel Session Started', value: 'ONSESSIONSTART' },
	{ name: 'Order About to Be Deleted', value: 'ONSALEBEFOREORDERDELETE' },
	{ name: 'Order Deleted', value: 'ONORDERDELETED' },
	{ name: 'Order Property Value Deleted', value: 'ONPROPERTYVALUEDELETED' },
	{ name: 'Order Property Value Saved', value: 'ONPROPERTYVALUEENTITYSAVED' },
	{ name: 'Order Saved (ONORDERENTITYSAVED)', value: 'ONORDERENTITYSAVED' },
	{ name: 'Order Saved (ONSALEORDERSAVED)', value: 'ONSALEORDERSAVED' },
	{ name: 'Payment Deleted', value: 'ONPAYMENTDELETED' },
	{ name: 'Payment Saved', value: 'ONPAYMENTENTITYSAVED' },
	{ name: 'Shipment Deleted', value: 'ONSHIPMENTDELETED' },
	{ name: 'Shipment Saved', value: 'ONSHIPMENTENTITYSAVED' },
	{ name: 'Task Added', value: 'ONTASKADD' },
	{ name: 'Task Comment Added', value: 'ONTASKCOMMENTADD' },
	{ name: 'Task Comment Deleted', value: 'ONTASKCOMMENTDELETE' },
	{ name: 'Task Comment Updated', value: 'ONTASKCOMMENTUPDATE' },
	{ name: 'Task Deleted', value: 'ONTASKDELETE' },
	{ name: 'Task Updated', value: 'ONTASKUPDATE' },
	{ name: 'Telephony Call Ended', value: 'ONVOXIMPLANTCALLEND' },
	{ name: 'Telephony Call Initialised', value: 'ONVOXIMPLANTCALLINIT' },
	{ name: 'Telephony Call Started', value: 'ONVOXIMPLANTCALLSTART' },
	{ name: 'User Added', value: 'ONUSERADD' },
	{ name: 'Workgroup Added', value: 'ONSONETGROUPADD' },
	{ name: 'Workgroup Deleted', value: 'ONSONETGROUPDELETE' },
	{ name: 'Workgroup Updated', value: 'ONSONETGROUPUPDATE' },
];
